/** 任务书 16.2 知识卡片类型 */
export enum KnowledgeCardType {
  DISPUTE_FOCUS = 'DISPUTE_FOCUS', // 争议焦点卡
  EVIDENCE_STRATEGY = 'EVIDENCE_STRATEGY', // 证据策略卡
  JUDGMENT_RULE = 'JUDGMENT_RULE', // 裁判规则卡
  DOCUMENT_DRAFTING = 'DOCUMENT_DRAFTING', // 文书表达卡
  CLIENT_COMMUNICATION = 'CLIENT_COMMUNICATION', // 客户沟通卡
  PRICING = 'PRICING', // 报价经验卡
  PRODUCT_DELIVERY = 'PRODUCT_DELIVERY', // 产品交付卡
  COURT_TRIAL = 'COURT_TRIAL', // 庭审经验卡
  MEDIATION = 'MEDIATION', // 调解谈判卡
  FAILURE_LESSON = 'FAILURE_LESSON', // 失败教训卡
  INDUSTRY_RISK = 'INDUSTRY_RISK', // 行业风险卡
  COMPLIANCE = 'COMPLIANCE', // 运营合规卡
}
